config/routes.rb
Rails.application.routes.draw do
  resources :transactions do
    member do
      get 'send_payout' 
      post 'process_payout' 
    end
  end
  resources :farmers
  get 'invest/index'
  get 'invest/success'
  get '/transactions/success', to: 'transactions#success', as: 'transactions_success'
  post '/send_sms', to: 'invest#send_sms'
  post '/stkpush', to: 'invest#stkpush'
  # post 'send_sms', to: 'sms#send_sms', as: :send_sms
  resources :investments do
    member do
      post 'invest'
    end
  end 
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/investment.rb
class Investment < ApplicationRecord
    
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController

  def index
    @investments = Investment.all

    @investments.each_with_index do |investment, index|
      investment.update(image_url: "nafaka#{index + 2}.jpg")
    end
  end

  def show
    @investment = Investment.find(params[:id])
  end

  def invest
    investment = Investment.find(params[:id])
    current_user.investments << investment
    redirect_to investments_path, notice: 'Investment successful!'
  end

end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_investment.html.erb
<div id="<%= dom_id investment %>">
  <% farmer_names = [
      "Wanjohi",
      "Tola",
      "Adensami",
      "Otieno",
      "Wambui",
      "Wanyama",
      "Juma",
      "Rashid",
      "Trevor",
      "Mandela"
  ] %>

  <div class="image-box">
    <%= image_tag "nafaka2.jpg", class: "product-image" %>
  </div>
  
  <div class="product-dets">
    <h1>
      <%= investment.title %>
    </h1>

    <p>
      <strong>Description:</strong>
      <%= investment.description %>
    </p>

    <p>
      <strong>Amount:</strong>
      <%= number_to_currency(investment.amount) %>
    </p>

    <p>
      <strong>Registered Farmer:</strong>
      <%= farmer_names[investment.id - 1] %> <span class="farmer">Verified</span>
    </p>
    
    <%= link_to "Back", investments_path, class: "btn btn-outline-secondary" %> | 
    <%= link_to "Invest", invest_index_path, class: "btn btn-outline-success" %>
    <br />
  </div>
</div>

app/views/investments/index.html.erb
<h1 class = "text-center">Investment Opportunities</h1>
<br />
<% farmer_names = [
        "Wanjohi",
        "Tola",
        "Adensami",
        "Otieno",
        "Wambui",
        "Wanyama",
        "Juma",
        "Rashid",
        "Trevor",
        "Mandela"
    ] %>

<div class="row">
  <% Investment.all.each_with_index do |investment, index| %>
    <div class="col-md-4">
      <div class="card fixed-height-card">
        <%= link_to investment_path(investment) do %>
          <%= image_tag investment.image_url, class: "card-img-top fixed-size" %>
        <% end %>
        <div class="card-body card-index">
          <h5 class="card-title"><%= investment.title %></h5>
          <p class="card-text"><%= investment.description %></p>
          <p class="card-text"><%= number_to_currency(investment.amount) %></p>

          <p class="card-text">
            <% farmer_name = farmer_names[index] %>
            <%= farmer_name %>
            <span class="farmer">Verified</span>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/investments/show.html.erb
<p class="notice" style="color: green;"><%= notice %></p>
<br />

<div class="product-details">
  <%= render @investment %>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<br />
<br />
<br />



<br />
<br />
<br />

<br />
<hr>

<div class="reasons-to-invest">
    <h2>Reasons to Invest</h2>
    <p>
        Be a part of transforming the poultry industry with our chicken rearing investment opportunity.
        With a proven track record of success and a commitment to sustainable practices, we're poised to revolutionize how chickens are raised and sold. Join us and benefit from our strong financial foundation, experienced leadership, and growing market demand.
    </p>
    <p>
        <strong>Key Highlights:</strong>
        <ul>
            <li>Impressive capital raise history and investor growth</li>
            <li>Experienced industry leaders driving our mission</li>
            <li>Consistent revenue growth over the past years</li>
        </ul>
    </p>
</div>

<div class="investment-overview">
    <h2>Overview</h2>
    <p>
        At Nafaka, we're revolutionizing the agricultural industry by providing funding to aspiring farmers like Wanjohi. With a focus on sustainable practices and responsible growth, we're offering investors the opportunity to support a agricultural ventures that promises significant returns.
    </p>
    <p>
        Wanjohi has a solid plan in place to rear and grow chickens in a state-of-the-art facility, ensuring their well-being and maximizing profitability. By investing in this venture, you're not just funding a business – you're contributing to a more sustainable and efficient food production process.
    </p>
    <h3>Stages of Chicken Rearing</h3>
    <ol>
        <li>Buying Fertilized Eggs: Wanjohi will begin by sourcing high-quality fertilized eggs for incubation.</li>
        <li>Incubation Phase: The eggs will be carefully incubated under controlled conditions to ensure healthy embryo development.</li>
        <li>Chick Feeding and Care: Once hatched, the chicks will receive special care and a balanced diet to promote growth.</li>
        <li>Health and Treatment: Regular health check-ups and treatments will be provided to maintain the well-being of the chicks.</li>
        <li>Growing Phase: As the chicks grow, they will be transitioned to larger spaces to allow them to thrive.</li>
        <li>Final Stage: When the chickens are fully grown, they will be ready for sale, and investors will start to see returns on their investment.</li>
    </ol>
    <p>
        Throughout these stages, you'll receive SMS updates to keep you informed about the progress of the venture and the status of your investment.
    </p>
</div>


<div class="about">
    <h2>About</h2>
    <p>
        Nafaka is dedicated to fostering innovation in agriculture. Our platform connects visionary farmers like Wanjohi with investors like you who share a passion for sustainable food production. With a team of experienced experts and a commitment to transparency, we're changing the way agriculture is funded and creating opportunities for growth.
    </p>
    <p>
        Wanjohi's chicken rearing project aligns perfectly with our values, and we're excited to bring this opportunity to our community of investors. Join us in supporting Wanjohi's journey towards a more profitable and environmentally conscious poultry business.
    </p>
</div>

<div class="terms">
    <h2>Terms</h2>
    <p>
        Invest in Wanjohi's chicken rearing venture with an investment of $1,000. As an investor, you'll own a stake in Wanjohi's project and have the potential to reap substantial profits as the venture grows.
    </p>
    <p>
        Don't miss this chance to be part of a transformative journey in agriculture. Your investment will not only support Wanjohi's business but also contribute to the advancement of sustainable and responsible farming practices.
    </p>
</div>

<div class="profits">
    <h2>Profits</h2>
    <p>
        By investing in Wanjohi's chicken rearing venture, you'll have the opportunity to earn substantial profits as the project succeeds. <strong> As the chickens grow and are sold for profit, you'll receive a portion of the earnings in return for your investment.</strong>
    </p>
    <p>
        Our platform ensures transparency and regular updates, so you can track the progress of Wanjohi's venture and stay informed about your potential returns. Join us in supporting Wanjohi and enjoy the rewards of sustainable investing.
    </p>
</div>