config/routes.rb
Rails.application.routes.draw do
  resources :transactions do
    member do
      get 'send_payout' 
      post 'process_payout' 
    end
  end
  resources :farmers
  get 'invest/index'
  get 'invest/success'
  get '/transactions/success', to: 'transactions#success', as: 'transactions_success'
  post '/send_sms', to: 'invest#send_sms'
  post '/stkpush', to: 'invest#stkpush'
  # post 'send_sms', to: 'sms#send_sms', as: :send_sms
  resources :investments do
    member do
      post 'invest'
    end
  end 
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/invest_controller.rb
class InvestController < ApplicationController

  EXCHANGE_RATE_USD_TO_KES = 126.6014
  def index
    
    @currency = params[:currency] || 'USD'
  @prices = Investment.all.map do |product|
    product.amount * EXCHANGE_RATE_USD_TO_KES
  end
  end
  def success
    
  end

  require 'rest-client'

    def stkpush
        phoneNumber = params[:phoneNumber]
        amount = "1"
        url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
        timestamp = "#{Time.now.strftime "%Y%m%d%H%M%S"}"
        business_short_code = ENV["MPESA_SHORTCODE"]
        password = Base64.strict_encode64("#{business_short_code}#{ENV["MPESA_PASSKEY"]}#{timestamp}")
        payload = {
        'BusinessShortCode': business_short_code,
        'Password': password,
        'Timestamp': timestamp,
        'TransactionType': "CustomerPayBillOnline",
        'Amount': amount,
        'PartyA': phoneNumber,
        'PartyB': business_short_code,
        'PhoneNumber': phoneNumber,
        'CallBackURL': "#{ENV["CALLBACK_URL"]}/callback_url",
        'AccountReference': 'Codearn',
        'TransactionDesc': "Payment for Codearn premium"
        }.to_json

        headers = {
        Content_type: 'application/json',
        Authorization: "Bearer #{get_access_token}"
        }

        response = RestClient::Request.new({
        method: :post,
        url: url,
        payload: payload,
        headers: headers
        }).execute do |response, request|
        case response.code
        when 500
        [ :error, JSON.parse(response.to_str) ]
        when 400
        [ :error, JSON.parse(response.to_str) ]
        when 200
        [ :success, JSON.parse(response.to_str) ]
        else
        fail "Invalid response #{response.to_str} received."
        end
        end
        render json: response
        # format.html { render :success }
        # format.json { render response }
    end

  def send_sms
    # Set your app credentials
    username = "valeria"
      apikey = "a91bf656d1ef72542dcbfe7b650e1263c08616ca9a71bf32f304699541cf86ce"
    
      # Initialize the SDK
      @AT = AfricasTalking::Initialize.new(username, apikey)
    
      sms = @AT.sms
    # Retrieve the Current user's details from the database

    to = params[:phone_number]
    
      # Send the welcome message
      message = "Welcome to Nafaka! Thank you for investing in Wanjohi's project. Expect SMS updates on the status. Stay tuned and have a great day!"
      
      # Set your shortCode or senderId
      # from = "Vaxx-Alerts"
    
      options = {
        "to" => to,
        "message" => message
        # "from" => from
      }
    
      begin
        # Send the SMS and retrieve the response
        response = sms.send(options)
    
        # Log success or any necessary information
        Rails.logger.info "SMS sent successfully"
      rescue AfricasTalking::AfricasTalkingException => ex
        # Log error or any necessary information
        Rails.logger.error "Failed to send SMS: #{ex.message}"
      end
      
    end

    private

    def generate_access_token_request
        @url = "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"
        @consumer_key = ENV['MPESA_CONSUMER_KEY']
        @consumer_secret = ENV['MPESA_CONSUMER_SECRET']
        @userpass = Base64::strict_encode64("#{@consumer_key}:#{@consumer_secret}")
        headers = {
            Authorization: "Bearer #{@userpass}"
        }
        res = RestClient::Request.execute( url: @url, method: :get, headers: {
            Authorization: "Basic #{@userpass}"
        })
        res
    end

    def get_access_token
        res = generate_access_token_request()
        if res.code != 200
        r = generate_access_token_request()
        if res.code != 200
        raise MpesaError('Unable to generate access token')
        end
        end
        body = JSON.parse(res, { symbolize_names: true })
        token = body[:access_token]
        AccessToken.destroy_all()
        AccessToken.create!(token: token)
        token
    end
end

app/helpers/invest_helper.rb
module InvestHelper
end

app/views/invest/index.html.erb
<div>
<!-- ARTICLE -->
	<div class="container mt-5">
    <div  class="mx-auto" style="width: 400px;"><h2>Invest With Wanjohi!</h2></div>
	<div class="row" style="padding: 50px;">

  <%
=begin%>
 <%= form_tag('/', method: :get) do %>
  <div class="currency-switcher">
    <select name="currency">
      <option value="USD">USD</option>
      <option value="KES">KES</option>
      <option value="NGN">Naira</option>
      <option value="CHIMONEY">Chimoney</option>
    </select>
  </div>
<% end %> 
<%
=end%>

  

		<div class="col">
        <%
=begin%>
 <div><button type="button" class="btn btn-outline-primary btn-lg" >KSH 145,000</button></div> 
<%
=end%>
		<p style="padding-top: 30px;">Invest in Wanjohi's chicken rearing venture with an investment of $5. As an investor, you'll own a stake in Wanjohi's project and have the potential to reap substantial profits as the venture grows.
		</p>
        <!-- Number input -->
        <%
=begin%>
 <p>Please enter your phone number to start receiving status updates on your investment</p>

<%= form_tag send_sms_path, method: :post do %>

  <div>
    <%= label_tag :phone_number, 'Phone Number:' %> <br />
    <%= text_field_tag :phone_number, nil, placeholder: 'Enter phone number' %>
  </div>
  <br />

  <%= submit_tag 'Send SMS', class: "btn btn-outline-primary" %>
<% end %>
<br />
<p>Please enter your phone number to pay via MPESA</p>
<%= form_tag stkpush_path, method: :post do %>

  <div>
    <%= label_tag :phoneNumber, 'Phone Number:' %> <br />
    <%= text_field_tag :phoneNumber, nil, placeholder: 'Enter phone number' %>
  </div>
  <br />

  <%= submit_tag 'Pay with Mpesa', class: "btn btn-outline-primary" %>
  <br />
  <br />
  <br />
  
<% end %> 
<%
=end%>
<%= link_to "Pay with Chimoney", new_transaction_path, class: "btn btn-outline-primary" %>
        </div>
        <div class="col">
            <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                      How much profit should i expect
                    </button>
                  </h2>
                  <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the first item's accordion body.</div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="flush-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                      how do i make farm schedule visits
                    </button>
                  </h2>
                  <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the second item's accordion body. Let's imagine this being filled with some actual content.</div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="flush-headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                      Amount of shares received
                    </button>
                  </h2>
                  <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the third item's accordion body. Nothing more exciting happening here in terms of content, but just filling up the space to make it look, at least at first glance, a bit more representative of how this would look in a real-world application.</div>
                  </div>
                </div>
              </div>
            </div>
            
            
        </div>
        
	</div>
    
</div>


<script>


</script>

app/views/invest/success.html.erb
<div>
  <br />
  <br />
  <br />
  <br />
  <div class="text-center">
    <h2>Your payment is successfully initiated!</h2>
    <p>
      Thank you for expressing interest in this project. You will receive a payment request in your email and also status updates on the project via SMS after successful completion of payment.
    </p>
  </div>
  <br />
  <br />
  <hr />
  <br />
  <br />

  <!-- Cost Breakdown -->
  <div class="text-center">
    <h3>Cost Breakdown for This Project</h3>
    <p>Here's a breakdown of where your investment will go:</p>
  </div>

  <!-- Sourcing Chicks -->
  <div class="text-left">
    <h4>Sourcing Chicks</h4>
    <ul>
      <li>We source 1-3-day old chicks and vaccinate them against Marek’s at Ksh. 100.</li>
      <li>A total of 1000 will be bought, and that will cost Sh. 100,000.</li>
    </ul>
  </div>

  <!-- Poultry Feeds -->
  <div class="text-left">
    <h4>Poultry Feeds</h4>
    <ul>
      <li>Chicks are fed on chick mash up to the 8th week, consuming an average of 60 grams per day, with each Kg costing ksh. 50.</li>
      <li>Growers mash will be required, from the 9th week to the 19th week, averaging 90 grams per day, with each Kg priced at ksh. 35.</li>
      <li>Additionally, layers mash is required, and it's fed from the 18th week to the 72nd week, with an average daily consumption of 140 grams per day. Each kg retails at kshs 42.</li>
    </ul>
  </div>

  <!-- Veterinary Costs -->
  <div class="text-left">
    <h4>Veterinary Costs</h4>
    <p>Vaccination of the chicks against chicken diseases like Gumboro will be done. It will be done against: Gumboro 1st dose, Gumboro 2nd dose, Newcastle 1st dose, Newcastle 2nd dose, Fowl typhoid, Deworming, and Vitamins.</p>
  </div>

  <!-- Poultry Equipment -->
  <div class="text-left">
    <h4>Poultry Equipment</h4>
    <ul>
      <li>Equipment such as feeders and drinkers will be required. 1.5 kg feeders/waterers retail at kshs 150, and each 10 kg feeders/waterers retail at kshs 700.</li>
      <li>Chicken cages for 128 birds retail at kshs 30,000.</li>
    </ul>
  </div>




</div>

<!-- Expected Revenue and Share Table -->
<div class="text-center">
  <h3>Expected Revenue and Share</h3>
  <p>After 75 weeks, here's what you can expect:</p>
  <table class="table">
    <thead>
      <tr>
        <th>Expected Revenue</th>
        <th>Your Share</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Ksh. 150,000</td>
        <td>70%</td>
      </tr>
    </tbody>
  </table>
</div>