config/routes.rb
Rails.application.routes.draw do
  resources :transactions do
    member do
      get 'send_payout' 
      post 'process_payout' 
    end
  end
  resources :farmers
  get 'invest/index'
  get 'invest/success'
  get '/transactions/success', to: 'transactions#success', as: 'transactions_success'
  post '/send_sms', to: 'invest#send_sms'
  post '/stkpush', to: 'invest#stkpush'
  # post 'send_sms', to: 'sms#send_sms', as: :send_sms
  resources :investments do
    member do
      post 'invest'
    end
  end 
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:index, :send_payout, :process_payout]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @investments = Investment.all
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        #send_sms
        send_money_via_chimoney(@transaction.investment.amount)
        format.html { redirect_to invest_success_url, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_payout
    @transaction = Transaction.find(params[:id])
  end

  def process_payout
    require 'uri'
    require 'net/http'

    url = URI("https://api-v2-sandbox.chimoney.io/v0.2/payouts/chimoney")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    @transaction = Transaction.find(params[:id])
    phone = @transaction.number
    phone_number = "+#{phone}"

    email = @transaction.email

    amount = params[:amount]

    request = Net::HTTP::Post.new(url)
    request["accept"] = 'application/json'
    request["content-type"] = 'application/json'
    request["X-API-KEY"] = 'bdf360cd6f2b0435d90395368225b5cde1cd376466c281c1af2b1c707a41205e'
    request.body = "{\"chimoneys\":[{\"email\":\"#{email}\",\"phone\":\"#{phone_number}\",\"valueInUSD\":#{amount}}]}"

    response = http.request(request)

    # Handle the response as needed

    redirect_to @transaction, notice: 'Payout sent successfully'
  end

  def success
    
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def send_sms
    # Set your app credentials
    username = "valeria"
      apikey = "a91bf656d1ef72542dcbfe7b650e1263c08616ca9a71bf32f304699541cf86ce"
    
      # Initialize the SDK
      @AT = AfricasTalking::Initialize.new(username, apikey)
    
      sms = @AT.sms
    # Retrieve the Current user's details from the database
    phone_number = @transaction.number
      to = "+#{phone_number}"
    
      # Send the welcome message
      message = "Welcome #{@transaction.name} to Nafaka! Thank you for investing in Wanjohis project. Expect SMS updates on the status. Stay tuned and have a great day!"
      
      # Set your shortCode or senderId
      # from = "Vaxx-Alerts"
    
      options = {
        "to" => to,
        "message" => message
        # "from" => from
      }
    
      begin
        # Send the SMS and retrieve the response
        response = sms.send(options)
    
        # Log success or any necessary information
        Rails.logger.info "SMS sent successfully"
      rescue AfricasTalking::AfricasTalkingException => ex
        # Log error or any necessary information
        Rails.logger.error "Failed to send SMS: #{ex.message}"
      end
      
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:name, :email, :number, :investment_id)
    end

    #Initiate chimoney payment
    def send_money_via_chimoney(amount)
      require 'uri'
      require 'net/http'
  
      url = URI("https://api-v2-sandbox.chimoney.io/v0.2/payouts/chimoney")
  
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true

      phone = @transaction.number
      phone_number = "+#{phone}"
      amount = @transaction.investment.amount
      email = @transaction.email
  
      request = Net::HTTP::Post.new(url)
      request["accept"] = 'application/json'
      request["content-type"] = 'application/json'
      request["X-API-KEY"] = 'bdf360cd6f2b0435d90395368225b5cde1cd376466c281c1af2b1c707a41205e'
      # request.body = "{\"subAccount\":\"dae06145-e1c8-4485-be0d-d00f2623c021\",\"momos\":[{\"momoCode\":\"MPX\",\"valueInUSD\":#{amount},\"phoneNumber\":\"#{phone_number}\",\"countryToSend\":\"Kenya\"}]}"
      request.body = "{\"chimoneys\":[{\"payerEmail\":\"otienostan96@gmail.com\",\"valueInUSD\":#{amount}}]}"
  
      http.request(request)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Your Name" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email, "Your Email Address" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :number, "Your Phone Number (format - 254...)" %>
    <%= form.text_field :number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :investment_id, "Select Investment" %>
    <%= form.collection_select :investment_id, @investments, :id, :title, { prompt: "Select an Investment" }, class: "form-control" %>
  </div>
<br />
  <div class="form-group">
    <%= form.submit "Initiate now via Chimoney", class: "btn btn-outline-success" %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Name:</strong>
    <%= transaction.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= transaction.email %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= transaction.number %>
  </p>

  <p>
    <strong>Investment:</strong>
    <%= Investment.find(transaction.investment_id).title %>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Investors</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Number</th>
      <th>Investment</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.name %></td>
        <td><%= transaction.email %></td>
        <td><%= transaction.number %></td>
        <td><%= Investment.find(transaction.investment_id).title %></td>
        <td>
          <%= link_to "Show more", transaction %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%
=begin%>
 <%= link_to "New transaction", new_transaction_path %> 
<%
=end%>

app/views/transactions/new.html.erb
<h1 class="text-center">Transaction Form Details</h1>
<p>Input details to initiate payment request via Chimoney and start getting SMS updates </p>
<%= render "form", transaction: @transaction %>

<br>

app/views/transactions/send_payout.html.erb
<h1>Send Payout to <%= @transaction.name %></h1>

<%= form_tag process_payout_transaction_path(@transaction), method: :post do %>
  <div class="form-group">
    <%= label_tag 'amount', 'Amount:' %>
    <%= number_field_tag 'amount', nil, class: 'form-control' %>
  </div>
<br />
  <%= submit_tag 'Send Payout', class: 'btn btn-primary' %>
<% end %>
<br />

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to send_payout_transaction_path(@transaction), class: 'btn btn-outline-success' do %>
  Send Payout
<% end %>
 |
  <%= link_to "Back", transactions_path, class: "btn btn-outline-primary" %>

  <%
=begin%>
 <%= button_to "Destroy this transaction", @transaction, method: :delete %> 
<%
=end%>
</div>
<br />
<br />

app/views/transactions/success.html.erb
  <br />
  <br />
  <br />
  <br />
  <div class="text-center">
    <h2>Payout has been sent successfully!</h2>
    <p>
      We will notify the investor of the payment made.
    </p>
  </div>
  <br />
  <br />
  <hr />
  <br />
  <br />